# BetterManhunt Configuration File

# Default headstart duration in seconds
# This is the time that runners have before hunters can move
default-headstart-duration: 30

# Compass update interval in seconds
# How often the hunting compass updates to point to the nearest runner
compass-update-interval: 5

# Chat settings
# Should team chat be enabled by default?
default-team-chat: false

# Game settings
# How long to display the game end screen before resetting to lobby (in seconds)
game-end-display-time: 10

# World settings
# Folder name for custom generated worlds
custom-worlds-folder: "ManhuntWorlds"

# Lobby settings
# The lobby location is set via the /manhunt setlobby command
# and will be saved here automatically
lobby:
  # This will be populated when you use /manhunt setlobby
  # world: world
  # x: 0
  # y: 64
  # z: 0
  # yaw: 0
  # pitch: 0
